

name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - main
      - dev
      - QA
      - preprod

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Determine suffix, tag, and service name
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            suffix=""
            service="backend"
            mongo_uri="${{ secrets.MONGO_URI }}"
            environment="${{ secrets.PROD_SERVE }}"
          elif [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            suffix="-dev"
            service="backend-dev"
            mongo_uri="${{ secrets.DEV_MONGO_URI }}"
            environment="${{ secrets.DEV_SERVE }}"
          elif [[ "${{ github.ref }}" == "refs/heads/QA" ]]; then
            suffix="-qa"
            service="backend-qa"
            mongo_uri="${{ secrets.QA_MONGO_URI }}"
            environment="${{ secrets.QA_SERVE }}"
          else
            suffix="-preprod"
            service="backend-preprod"
            mongo_uri="${{ secrets.MONGO_URI_PREPROD }}"
            environment="${{ secrets.PREPROD_SERVE }}"
          fi
          tag="gcr.io/${{ secrets.GCP_PROJECT_ID }}/${service}:${GITHUB_SHA}"
          echo "Service name: $service"
          echo "Tag: $tag"
          echo "suffix=${suffix}" >> $GITHUB_ENV
          echo "service=${service}" >> $GITHUB_ENV
          echo "tag=${tag}" >> $GITHUB_ENV
          echo "mongo_uri=${mongo_uri}" >> $GITHUB_ENV
          echo "environment=${environment}" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag ${{ env.tag }} .

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.service }} \
            --image ${{ env.tag }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --set-env-vars "CLOUDINARY_URL=${{ secrets.CLOUDINARY_URL }},FRONTEND_URL=${{ secrets.FRONTEND_URL }},EMAIL_HOST=${{ secrets.EMAIL_HOST }},EMAIL_PASS=${{ secrets.EMAIL_PASS }},EMAIL_USER=${{ secrets.EMAIL_USER }},BUCKET_NAME=${{ secrets.BUCKET_NAME }},JWT_SECRET=${{ secrets.JWT_SECRET }},MONGO_URI=${{ env.mongo_uri }},ENVIRONMENT=${{ env.environment }}"

